// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SkipTitle","status":true,"description":"","parameters":{}},
{"name":"XdRs_BubbleDialog","status":false,"description":"气泡对话框。","parameters":{}}
];
